Use dayOfWeek as key when rendering days
```
components/VHours.vue:4:64 - error TS2339: Property 'id' does not exist on type 'Day'.

4       <template v-for="day in possiblyCondensedDays" :key="day.id">
                                                                 ~~

Found 1 error in components/VHours.vue:4
```