Use public object on useRuntimeConfig
The typings for useRuntimeConfig improved.

```
❯ pages/reviews.vue:21:28 - error TS2322: Type 'unknown' is not assignable to type 'string'.

21 await reviewsStore.fetch({ apiBase })
                              ~~~~~~~

  store/reviews.ts:35:33
    35     async fetch ({ apiBase }: { apiBase: string }) {
                                       ~~~~~~~
    The expected type comes from property 'apiBase' which is declared here on type '{ apiBase: string; }'

Found 1 error in pages/reviews.vue:21
```